# Generated by Django 5.2.3 on 2025-06-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='tree',
        ),
        migrations.AddField(
            model_name='tree',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='trees', to='trees.image'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tree',
            name='plant_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
