# Generated by Django 5.2.3 on 2025-06-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0002_remove_image_tree_tree_images_alter_tree_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='sex',
            field=models.CharField(blank=True, choices=[('bisexual', 'สมบูรณ์เพศ'), ('male', 'ตัวผู้'), ('female', 'ตัวเมีย'), ('monoecious', 'แยกเพศในต้นเดียวกัน'), ('mixed', 'ผสมหลายเพศ'), ('unknown', 'ไม่ระบุ/ไม่แน่ใจ')], default='unknown', max_length=20),
        ),
    ]
