# Generated by Django 5.2.3 on 2025-06-28 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0003_tree_sex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tree',
            old_name='main_characteristics',
            new_name='phenotype',
        ),
    ]
