# Generated by Django 5.2.3 on 2025-06-28 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0004_rename_main_characteristics_to_phenotype'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='clone_source',
            field=models.ForeignKey(blank=True, help_text='อ้างอิงถึงต้นแม่ที่ใช้ในการปักชำ (Clone Source)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='trees.tree'),
        ),
        migrations.AddField(
            model_name='tree',
            name='disease_notes',
            field=models.TextField(blank=True, help_text='บันทึกโรคหรือปัญหาศัตรูพืชที่พบในต้นนี้'),
        ),
        migrations.AddField(
            model_name='tree',
            name='document_url',
            field=models.URLField(blank=True, help_text='ลิงก์หรือไฟล์เอกสารที่เกี่ยวข้องกับต้นนี้', null=True),
        ),
        migrations.AddField(
            model_name='tree',
            name='flower_quality',
            field=models.TextField(blank=True, help_text='คุณภาพหรือคุณสมบัติของดอก เช่น สี กลิ่น ขนาด ฯลฯ'),
        ),
        migrations.AddField(
            model_name='tree',
            name='genotype',
            field=models.CharField(blank=True, help_text='ข้อมูลพันธุกรรมของต้นไม้ (ถ้ามี)', max_length=100),
        ),
        migrations.AddField(
            model_name='tree',
            name='parent_female',
            field=models.ForeignKey(blank=True, help_text='อ้างอิงถึงต้นแม่พันธุ์ของต้นนี้ (ใช้ในงานเพาะพันธุ์/ผสมเกสร)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mothered_trees', to='trees.tree'),
        ),
        migrations.AddField(
            model_name='tree',
            name='parent_male',
            field=models.ForeignKey(blank=True, help_text='อ้างอิงถึงต้นพ่อพันธุ์ของต้นนี้ (ใช้ในงานเพาะพันธุ์/ผสมเกสร)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fathered_trees', to='trees.tree'),
        ),
        migrations.AddField(
            model_name='tree',
            name='pollinated_by',
            field=models.ForeignKey(blank=True, help_text='อ้างอิงถึงต้นที่ใช้ผสมเกสรกับต้นนี้', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pollinated_offspring', to='trees.tree'),
        ),
        migrations.AddField(
            model_name='tree',
            name='pollination_date',
            field=models.DateField(blank=True, help_text='วันที่ทำการผสมเกสร', null=True),
        ),
        migrations.AddField(
            model_name='tree',
            name='seed_count',
            field=models.PositiveIntegerField(blank=True, help_text='จำนวนเมล็ดที่ได้จากการผสมพันธุ์', null=True),
        ),
        migrations.AddField(
            model_name='tree',
            name='seed_harvest_date',
            field=models.DateField(blank=True, help_text='วันที่เก็บเมล็ดพันธุ์จากต้นนี้', null=True),
        ),
        migrations.AddField(
            model_name='tree',
            name='yield_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='ปริมาณผลผลิตที่ได้ต่อรอบ (กรัม)', max_digits=10, null=True),
        ),
    ]
