# Generated by Django 5.2.3 on 2025-06-28 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0005_add_document_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(help_text='รหัสประจำชุดการปลูก/เพาะพันธุ์', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='รายละเอียดเกี่ยวกับชุดการปลูก', null=True)),
                ('started_date', models.DateField(blank=True, help_text='วันที่เริ่มต้นชุดการปลูก', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ชื่อสายพันธุ์ของต้นไม้', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='รายละเอียดเพิ่มเติมของสายพันธุ์', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tree',
            name='document_url',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='species',
        ),
        migrations.AddField(
            model_name='tree',
            name='document',
            field=models.FileField(blank=True, help_text='อัปโหลดไฟล์เอกสารที่เกี่ยวข้องกับต้นนี้', null=True, upload_to='tree_documents/'),
        ),
        migrations.AddField(
            model_name='tree',
            name='germination_date',
            field=models.DateField(blank=True, help_text='วันที่เมล็ดเริ่มงอก', null=True),
        ),
        migrations.AddField(
            model_name='tree',
            name='growth_stage',
            field=models.CharField(blank=True, help_text='ระยะการเจริญเติบโต เช่น ต้นกล้า, โตเต็มวัย, ออกดอก', max_length=50),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(help_text='ไฟล์รูปภาพของต้นไม้', upload_to='tree_images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='วัน-เวลาที่อัปโหลดรูปภาพ'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='clone_source',
            field=models.ForeignKey(blank=True, help_text='ต้นแม่ที่ใช้ในการปักชำ (Clone Source)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='trees.tree'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='วัน-เวลาที่บันทึกข้อมูลต้นไม้'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='genotype',
            field=models.CharField(blank=True, help_text='รหัสพันธุกรรม หรือข้อมูลทางพันธุกรรมของต้นไม้ (ถ้ามี)', max_length=100),
        ),
        migrations.AlterField(
            model_name='tree',
            name='harvest_date',
            field=models.DateField(blank=True, help_text='วันที่เก็บเกี่ยว', null=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='images',
            field=models.ManyToManyField(blank=True, help_text='รูปภาพที่เกี่ยวข้องกับต้นไม้', related_name='trees', to='trees.image'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='location',
            field=models.CharField(blank=True, help_text='สถานที่ปลูกต้นไม้ เช่น โรงเรือน, แปลงปลูก ฯลฯ', max_length=255),
        ),
        migrations.AlterField(
            model_name='tree',
            name='nickname',
            field=models.CharField(blank=True, help_text='ชื่อเล่นหรือรหัสต้นไม้', max_length=100),
        ),
        migrations.AlterField(
            model_name='tree',
            name='notes',
            field=models.TextField(blank=True, help_text='บันทึกเพิ่มเติมเกี่ยวกับต้นไม้'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='parent_female',
            field=models.ForeignKey(blank=True, help_text='ต้นแม่พันธุ์ (ใช้ในงานเพาะพันธุ์/ผสมเกสร)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mothered_trees', to='trees.tree'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='parent_male',
            field=models.ForeignKey(blank=True, help_text='ต้นพ่อพันธุ์ (ใช้ในงานเพาะพันธุ์/ผสมเกสร)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fathered_trees', to='trees.tree'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='phenotype',
            field=models.TextField(blank=True, help_text='ลักษณะภายนอกหรือคุณสมบัติเด่นของต้นไม้'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='plant_date',
            field=models.DateField(blank=True, help_text='วันที่ย้ายปลูกลงแปลงหรือกระถาง', null=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='pollinated_by',
            field=models.ForeignKey(blank=True, help_text='ต้นที่ใช้ผสมเกสรกับต้นนี้', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pollinated_offspring', to='trees.tree'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='sex',
            field=models.CharField(blank=True, choices=[('bisexual', 'สมบูรณ์เพศ'), ('male', 'ตัวผู้'), ('female', 'ตัวเมีย'), ('monoecious', 'แยกเพศในต้นเดียวกัน'), ('mixed', 'ผสมหลายเพศ'), ('unknown', 'ไม่ระบุ/ไม่แน่ใจ')], default='unknown', help_text='เพศของต้นไม้', max_length=20),
        ),
        migrations.AlterField(
            model_name='tree',
            name='status',
            field=models.CharField(blank=True, help_text='สถานะปัจจุบันของต้นไม้ เช่น ปลูกอยู่, เก็บเกี่ยวแล้ว ฯลฯ', max_length=50),
        ),
        migrations.AlterField(
            model_name='tree',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='วัน-เวลาที่มีการแก้ไขข้อมูลล่าสุด'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='variety',
            field=models.CharField(blank=True, help_text='ชื่อพันธุ์ย่อย/ชื่อทางการค้า (ถ้ามี)', max_length=100),
        ),
        migrations.AddField(
            model_name='tree',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='ชุดหรือรอบการปลูก/เพาะพันธุ์', null=True, on_delete=django.db.models.deletion.SET_NULL, to='trees.batch'),
        ),
        migrations.AddField(
            model_name='tree',
            name='strain',
            field=models.ForeignKey(blank=True, help_text='สายพันธุ์ของต้นไม้', null=True, on_delete=django.db.models.deletion.SET_NULL, to='trees.strain'),
        ),
    ]
