# Generated by Django 5.2.3 on 2025-06-28 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0006_batch_strain_remove_tree_document_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='ชุดหรือรอบการปลูก/เพาะพันธุ์ (ต้องเลือกเสมอ)', null=True, on_delete=django.db.models.deletion.PROTECT, to='trees.batch'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='plant_date',
            field=models.DateField(help_text='วันที่ย้ายปลูกลงแปลงหรือกระถาง (ต้องกรอก)'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='sex',
            field=models.CharField(choices=[('bisexual', 'สมบูรณ์เพศ'), ('male', 'ตัวผู้'), ('female', 'ตัวเมีย'), ('monoecious', 'แยกเพศในต้นเดียวกัน'), ('mixed', 'ผสมหลายเพศ'), ('unknown', 'ไม่ระบุ/ไม่แน่ใจ')], default='unknown', help_text='เพศของต้นไม้ (ต้องเลือกเสมอ)', max_length=20),
        ),
        migrations.AlterField(
            model_name='tree',
            name='status',
            field=models.CharField(help_text='สถานะปัจจุบันของต้นไม้ เช่น ปลูกอยู่, เก็บเกี่ยวแล้ว ฯลฯ (ต้องกรอก)', max_length=50),
        ),
        migrations.AlterField(
            model_name='tree',
            name='strain',
            field=models.ForeignKey(help_text='สายพันธุ์ของต้นไม้ (ต้องเลือกเสมอ)', on_delete=django.db.models.deletion.PROTECT, to='trees.strain'),
        ),
    ]
