# Generated by Django 5.2.3 on 2025-07-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0007_alter_tree_batch_alter_tree_plant_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, help_text='รูปขนาดย่อ (สร้างอัตโนมัติหลังอัปโหลด)', null=True, upload_to='tree_images/thumbnails/'),
        ),
    ]
