# Generated by Django 5.2.3 on 2025-07-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0008_image_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='generation',
            field=models.CharField(blank=True, help_text='รุ่นของต้นไม้', max_length=50, null=True),
        ),
    ]
