# Generated by Django 5.2.8 on 2025-11-25 05:28

import django.db.models.deletion
import trees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0009_tree_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='tree',
            field=models.ForeignKey(blank=True, help_text='ต้นไม้ที่เป็นเจ้าของรูปภาพนี้', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_set', to='trees.tree'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(help_text='ไฟล์รูปภาพของต้นไม้', upload_to=trees.models.tree_image_path),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, help_text='รูปขนาดย่อ (สร้างอัตโนมัติหลังอัปโหลด)', null=True, upload_to=trees.models.tree_thumbnail_path),
        ),
    ]
