# Generated by Django 5.2.8 on 2026-01-26 02:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0010_image_tree_alter_image_image_alter_image_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateTimeField(default=django.utils.timezone.now, help_text='วัน-เวลาที่เกิดเหตุการณ์')),
                ('action_type', models.CharField(choices=[('water', 'รดน้ำเปล่า'), ('feed', 'รดน้ำใส่ปุ๋ย'), ('flush', 'Flush (ล้างดิน)'), ('prune', 'Pruning/Defoliation (ตัดแต่ง)'), ('train', 'LST/HST (ดัดกิ่ง)'), ('flip', 'Flip to Flower (ทำดอก)'), ('harvest', 'Harvest (เก็บเกี่ยว)'), ('dry', 'Start Drying (ตาก)'), ('cure', 'Start Curing (บ่ม)'), ('note', 'Note (บันทึกทั่วไป)'), ('photo', 'Photo Update (อัปเดตรูป)'), ('issue', 'Issue/Pest (พบปัญหา/แมลง)'), ('environment', 'Environment (สภาพแวดล้อม)'), ('other', 'อื่นๆ')], default='note', help_text='ประเภทของกิจกรรม', max_length=50)),
                ('title', models.CharField(blank=True, help_text='หัวข้อสั้นๆ (ถ้ามี)', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='รายละเอียด')),
                ('ph', models.DecimalField(blank=True, decimal_places=2, help_text='ค่า pH', max_digits=4, null=True)),
                ('ec', models.DecimalField(blank=True, decimal_places=2, help_text='ค่า EC (uS/cm หรือ ppm)', max_digits=5, null=True)),
                ('temp', models.DecimalField(blank=True, decimal_places=1, help_text='อุณหภูมิ (°C)', max_digits=4, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=1, help_text='ความชื้น (%)', max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tree', models.ForeignKey(help_text='ต้นไม้ที่บันทึก', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='trees.tree')),
            ],
            options={
                'ordering': ['-action_date'],
            },
        ),
        migrations.AddField(
            model_name='image',
            name='log',
            field=models.ForeignKey(blank=True, help_text='ลิงก์กับบันทึกเหตุการณ์ (ถ้ามี)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='trees.treelog'),
        ),
    ]
