# Generated by Django 5.2.8 on 2026-01-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0011_treelog_image_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='treelog',
            name='dry_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='น้ำหนักแห้ง (g)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='treelog',
            name='wet_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='น้ำหนักสด (g)', max_digits=8, null=True),
        ),
    ]
